name: PolyxUI Auto Build (CN) ( TEST )

on:
  workflow_dispatch:
    inputs:
      input_url:
        description: 'URL of the file to build'
        required: true

jobs:
  PolyxUI_Status:
    runs-on: ubuntu-latest
    steps:
      - name: Clean All Junk,App
        run: |
          docker rmi `docker images -q` || true
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/sudo apt/sources.list.d || true
          sudo apt -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell mysql* php* || true
          sudo apt -y autoremove --purge || true
          sudo apt -y autoclean || true
          sudo apt clean || true

      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          swap-size-mb: 1024
          root-reserve-mb: 512
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'

      - name: Checkout code
        uses: actions/checkout@main

      - name: Checkout WORKSPACE
        run: |
          
          git clone https://${{ secrets.PRIVATEP_TOKEN }}@github.com/ndtai1527/polyxui.git

      - name: Set up Time
        run: |
          echo "Setting Vienam timezone"
          sudo timedatectl set-timezone Asia/Ho_Chi_Minh

      - name: Install Stuff
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test 
          sudo apt-get update
          sudo apt-get install -y aria2 rclone sshpass wget python3 libc6 libstdc++6 python3-pip dialog libgtk-3-dev aapt busybox zip unzip p7zip-full zipalign zstd bc android-sdk-libsparse-utils xmlstarlet
          sudo pip3 install ConfigObj
          
      - name: Install OpenJDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: chmod branch
        run: |
          cd polyxui_branch
          sudo chmod 777 -R *

      - name: Making ROM...
        env:
          INPUT_URL: ${{ inputs.input_url }}
        run: |
          cd polyxui_branch
          ./polyxCN.sh "$INPUT_URL"
      
